name: Publish to Dockerhub

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Node.js 24.6.0
        uses: actions/setup-node@v4
        with:
          node-version: '24.6.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from tag
        id: version
        run: |
          # Extract version from tag (e.g., v1.0.3 or 1.0.3 -> 1.0.3)
          VERSION="${GITHUB_REF#refs/tags/}"
          VERSION="${VERSION#v}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "Extracted version: ${VERSION}"

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/purrito:${{ steps.version.outputs.tag }}
            ${{ secrets.DOCKER_USERNAME }}/purrito:${{ steps.version.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/purrito:latest
          labels: |
            org.opencontainers.image.version=${{ steps.version.outputs.version }}
            org.opencontainers.image.created=${{ github.event.release.published_at }}
            org.opencontainers.image.revision=${{ github.sha }}