name: Quality Assurance

on:
  push:
    branches: [ "master" ]
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

jobs:
  unitTesting:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ fromJson(steps.node.outputs.version).node-version }}
          cache: 'npm'
      - run: npm -w backend ci
      - run: npm -w backend run test

  lint:
    name: Linter
    runs-on: ubuntu-latest

    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ fromJson(steps.node.outputs.version).node-version }}
      - run: npm -w backend ci
      - run: npm -w backend run lint --if-present

      - name: Get Node.js version
        id: node
        run: echo "::set-output name=version::$(cat node-version.json)"