name: Quality Assurance

on:
  push:
    branches: [ "master" ]
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

jobs:
  unitTesting:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Get node version from package.json
        run: |
          echo "$(cat ./package.json)" | jq .engines.node | xargs -I {} echo "nodeVersion="{} >> $GITHUB_ENV
      - name: Use node version ${{ env.nodeVersion }} from package.json
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.nodeVersion }}
          cache: 'npm'
      - run: npm -w backend ci
      - run: npm -w backend run test

  lint:
    name: Linter
    runs-on: ubuntu-latest

    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm -w backend ci
      - run: npm -w backend run lint --if-present